server:
  port: 4000
  
spring:
    mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
            
            
    datasource:
       url: jdbc:mysql://localhost:3306/Olx_application
       username: root
       password: ROOT
       
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      
      
management:
  endpoints:
    web:
     exposure:
      include:
      - "*"
     # exclude:
      #- health
      #- info
     base-path: "/my-actuator"
         