server:
  port: 2000
  
spring:
    mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
            
    datasource:
       url: jdbc:mysql://localhost:3306/Olx_application
       username: root
       password: ROOT
       
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true